# Generated by Django 2.0.6 on 2018-06-18 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='comparator',
            name='result',
        ),
        migrations.AddField(
            model_name='compareddata',
            name='comparator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Comparator'),
        ),
        migrations.AddField(
            model_name='compareddata',
            name='item1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item1', to='mainapp.ScrapyItem'),
        ),
        migrations.AddField(
            model_name='compareddata',
            name='item2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item2', to='mainapp.ScrapyItem'),
        ),
    ]
